### ISSUE TITLE
US8: Form Entry

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/capstone-expiration-tracking-app#14]
### Value proposition
As a user
I want to be able to update new detail of the item
So that I can always re-use the exiting card item that I already created

### Description
![Image](https://user-images.githubusercontent.com/135506311/259029816-0b68d1e8-b76e-4f13-a4c2-0a54f6acf686.png)

### Acceptance criteria

- [ ] The form is displayed
- [ ] The heading is displayed
- [ ] The emoji input is displayed
- [ ] The name input is displayed
- [ ] The purchased date input is displayed
- [ ] The expiration date input is displayed
- [ ] The amount input is displayed
- [ ] The category input is displayed
- [ ] User is able to in put text in name input and amount input
- [ ] User is able to select date for purchased date input and Expiration date input
- [ ] User is able to select options for category input

### Tasks

- [ ] Create a new branch "feature/updateForm"
- [ ] Create Form component to render form and input field

size: M

**Comment by Roland-Hufnagel** [comment]
Good story! I am just wondering: If you update an existing item, shouldn't the input fields (at least name and category) have a default Value, that can be edited?

And in my opinion a form itself has no value for the user, as long as there is no 'save'-button. (in your value proposition you say: 'I want to update new Details of the item' => this includes the save function). But since I saw you have another US for that, it is okay for me.

**Comment by NirachaMarchett** [comment]
You pointed out something I completely missed and should have mentioned. The name, purchased date and expiration date should have default values! Thank you for your feedback! :)
