### ISSUE TITLE
US9: Submit button to display updated detail of the item card

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/capstone-expiration-tracking-app#15]
### Value proposition
As a user
Once I filled in all the form I want to be able to submit my input
So that the detail is updated to the item card

### Description
![Image](https://user-images.githubusercontent.com/135506311/259032649-79ffa2fe-0e4f-419e-af23-1b18e1c0d092.png)

### Acceptance criteria

- [ ] The button is displayed
- [ ] The button is display below the form field
- [ ] When user click on the button, the new details should be updated and displayed in the item card above
- [ ] The amount is displayed on the card
- [ ] The category is displayed on the card

### Tasks

- [ ] Create a new branch "feature/saveButton"
- [ ] Add button under the Form Component of Form Entry [US8](https://github.com/NirachaMarchett/capstone-expiration-tracking-app/issues/14)
- [ ] Create handleUpdate function to handle new input data

size: M

**Comment by Roland-Hufnagel** [comment]
Looks good.
