### ISSUE TITLE
US10: Delete button to delete card item

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/capstone-expiration-tracking-app#16]
### Value proposition
As a user
I want a delete button 
So that I am able to delete the item card that I don't need anymore

### Description
![Image](https://user-images.githubusercontent.com/135506311/259039474-a06990a8-10e7-4a8f-bbe6-044733496a99.png)

### Acceptance criteria

- [ ] The button is displayed
- [ ] The button is display below the form field
- [ ] When user click on the button, the card is deleted and user is directed back to the homepage

### Tasks

- [ ] Create a new branch "feature/deleteButton"
- [ ] Add button under the Form Component of Form Entry [US8](https://github.com/NirachaMarchett/capstone-expiration-tracking-app/issues/14)
- [ ] Create handleDelete function to handle item removal

size: M

**Comment by Roland-Hufnagel** [comment]
Looks good.
