### ISSUE TITLE
US4: Entry Form for Grocery Items

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/capstone-expiration-tracking-app#2]
### Value proposition

As a user
I want to be able to add more grocery item 
So that I can view it on the list later on

### Description

![Image](https://user-images.githubusercontent.com/135506311/257748763-9afbb8a2-6c6a-48b3-8feb-b17f48f55c60.png)

### Acceptance criteria

- [ ] An entry form is displayed.
- [ ] It includes 4 input fields( add emoji, Name, Purchased Date and Expiration Date)
- [ ] Name, Purchased Date and Expiration Date are required, add emoji is optional
- [ ] It includes a submit button "Add item"
- [ ] By clicking on the submit button, adds an item to the grocery list

### Task

- [ ] Create a feature branch "feature/addItemForm"
- [ ] Create "/Add" page.
- [ ] Create the “AddGroceryItemForm” component to render the form
- [ ] Prevent default from behaviour and refocus on first field.
- [ ] Create handleAddGroceryItem function that adds the grocery item to list when submit the form

size: M

**Comment by JudithRe** [comment]
What happens when no emoji is chosen? Is a default emoji displayed? Maybe add that to the tasks?
