### ISSUE TITLE
US11: Local Storage for data persistent

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/capstone-expiration-tracking-app#21]
### Value Proposition
As a user
I want the grocery Items I added stored somewhere
So that when I refresh the page the new added items don't disappear. 

### Description
Use the localStorage API provided by browsers to store data locally on the user's device. This should allow user to save data in the browser's storage and retrieve it even after a page refresh.

### Acceptance criteria

- [ ] After user refresh the page, the new added items should not disappear from the groceries list

### Tasks

- [ ] Create a new branch "feature/localStorage"
- [ ] Use Helper Function to make working with the Web Storage API easier

size: S

**Comment by JudithRe** [comment]
LGTM. But to really have the data in a safe place you could create a db.
