### ISSUE TITLE
US12: Sum of tracked items

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/capstone-expiration-tracking-app#22]
### Value proposition
As a user
I want to be able to see how many groceries items I am tracking
without having to count them myself.

### Description
![Image](https://user-images.githubusercontent.com/135506311/259382785-c2eb5cae-67ae-49dd-998c-a9f1974e0116.png)

### Acceptance 

- [ ] The total of tracking items is displayed as a number
- [ ] The total of tracking items is displayed above the list

### Tasks

- [ ] Create a new branch "feature/countTotal"
- [ ] Create a counter function that count the length of the groceriesList

size: S

**Comment by JudithRe** [comment]
lgtm
