### ISSUE TITLE
US13: Light/ Dark Mode Toggle Button

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/capstone-expiration-tracking-app#23]
### Value proposition
As a user
I want to be able to switch between light mode and dark mode
So that I am more flexible with the screen mode options

### Description
![Image](https://user-images.githubusercontent.com/135506311/259442708-1a252510-c44c-4278-8501-d0aa9886d596.png)

### Acceptance criteria

- [ ] The toggle button is displayed
- [ ] The toggle button is displayed on top of the page(inside a header)
- [ ] On toggle, the mode should switch between light mode and dark mode
- [ ] The toggle button is displayed in all pages (homepage, add page, item page)

### Tasks

- [ ] Create a new branch "feature/toggleButton"
- [ ] Create a Switch Component to render the toggle button

size: M

**Comment by StrongCurrent** [comment]
LGTM. Well done. Keep up the good work
