### ISSUE TITLE
US14: Search Tab

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/capstone-expiration-tracking-app#27]
As a user
I want to be able to search for recipes 
So that I know or get some inspiration on what I do with the soon to expire items 

### Description

![Image](https://user-images.githubusercontent.com/135506311/260382607-22273e3c-a33e-4299-ac9f-55464fdd2361.png)

### Acceptance criteria

- [ ] User is able to navigate to the recipes page
- [ ] Search bar is displayed
- [ ] Submit button is displayed
- [ ] Label is displayed
- [ ] Search bar is displayed at the upper part of the page
- [ ] On click, the result of suggested recipes are displayed below the search tab
- [ ] Each suggested recipe has image, name, time, ingredients and interaction display 
- [ ] User can access the ingredient and the instruction 

### Tasks

- [ ] Create a new brach "feature/recipeSearch"
- [ ] Create a Search bar Component
- [ ] Create a Recipe Component to render a list of result
- [ ] Fetch the data from the api
- [ ] Create handle search function for recipe search

size: L

**Comment by ninaassmann** [comment]
LGTM
