### ISSUE TITLE
US15: Favorite Button

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/capstone-expiration-tracking-app#28]
### Value proposition
As a user
I want to be able to save some recipes
So that I can easily find it in the future

### Description
![Image](https://user-images.githubusercontent.com/135506311/260392517-59945168-a917-4a5e-bd0f-eec343ec90f9.png)

### Acceptance criteria

- [ ] The favourite button is displayed on each of the suggested recipe
- [ ] Each button allows user to toggle between favourite and unfavourite  
- [ ] On favourite, the favourite recipe is added to the favourite list on the favourite page
- [ ] On unfavourite, the favourite recipe is removed from the favourite list on the favourite page
- [ ] User is able to navigate to the favourite page

### Tasks

- [ ] Create a new branch "feature/favouriteButton"
- [ ] Create a FavoriteButton Component to render favourite buttons on each suggested recipes
- [ ] Create a Favourite page
- [ ] Create handleFavourite function to handle favourite buttons

size: M
