### ISSUE TITLE
US2: Item Expiration Overview

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/capstone-expiration-tracking-app#5]
### Value proposition
As a user
I want to see an overview display
so that I know how many items are already expired, how many items are expiring in one day, and how many items are expiring in 2 days.

### Description
<img width="273" alt="Screenshot 2023-08-01 at 22 05 02" src="https://github.com/NirachaMarchett/recap-project-3_rick-and-morty-app/assets/135506311/80fc4c98-02d1-47b2-93bd-1877bcf99a88">

### Acceptance criteria

- [ ] Number of expired items, items that are expiring in 1 day, and in 2 days are displayed 
- [ ] The heading is displayed
- [ ] Sum of expired items is displayed
- [ ] Sum of items expiring in one day is displayed
- [ ] Sum of items expiring in two days is displayed

### Tasks

- [ ] Create new feature branch "feature/ExpirationsOverview
- [ ] Create the component "ExpirationsOverview" to render a list and the heading 
- [ ] Render the component "ExpirationsOverview" in the homepage (pages/ index.js)
- [ ] Create a filtering function and use it three times to calculate the counts of groceries that are expiring today, in one day, and in three days.  Then display them in the component.

size: M
