### ISSUE TITLE
US1: List of All Grocery Item Entries

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/capstone-expiration-tracking-app#6]
### Value proposition

As a user
I want to see a list of all my grocery items
so that I can get an overview of all the grocery items.  

### Description

![Image](https://user-images.githubusercontent.com/135506311/257235581-6dba5d40-e900-439c-9671-a0a76d57cccc.png)

### Acceptance criteria

- [ ] All grocery items are displayed as cards in a list
- [ ] Each grocery item displays an emoji as a heading
- [ ] Each grocery item's name is displayed
- [ ] Each grocery item's purchased date is displayed
- [ ] Each grocery item's expiration date is displayed
- [ ] Each grocery item's expiration countdown is displayed
- [ ] The list is scrollable

### Tasks

- [ ] Create a feature branch "feature/GroceriesList"
- [ ] Create a variable that contains an array of objects for groceries
- [ ] Create the component "GroceriesList" to render a list, which contains grocery item

size: M
