### ISSUE TITLE
US5: Search Bar

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/capstone-expiration-tracking-app#8]
### Value proposition
As a user
I want to search for item based on its name
So only item I am looking for appears on the list

### Description

![Image](https://user-images.githubusercontent.com/135506311/258077106-96c4e210-e76a-48e5-aea3-3c2dbf24bd82.png)

### Acceptance criterio

- [ ] The search bar is displayed
- [ ] The search bar has a place holder
- [ ] The reset button (Cancle) is displayed right next to the search bar
- [ ] User should be able to input text in the search bar
- [ ] Search result appears upon typing

### Task

- [ ] Create new feature branch "feature/searchBar"
- [ ] Create a search bar component
- [ ] Create cancel button next to the search bar
- [ ] Add functionality to the search bar

**Comment by florianblaschke** [comment]
LGTM!
