### ISSUE TITLE
US6: Navigation

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/capstone-expiration-tracking-app#9]
### Value proposition
As a user
I want to be able to switch between the homepage and the adding item page,
so that I can access the grocery list in the homepage and the form in the adding page.

### Description

![Image](https://user-images.githubusercontent.com/135506311/258088456-38693751-8c51-4517-8add-de3b7b3bb077.png)

### Acceptance criteria

- [ ] A two anchors is displayed
- [ ] The navigation is displayed at the bottom of the page
- [ ] User is able to move to homepage and form page by clicking on the anchors
- [ ] text "Home" and "Add" displayed below the anchors

### Tasks

- [ ] Create a feature branch "feature/Navigation"
- [ ] Create Navigation Component to render the navigation

**Comment by Bilal4317** [comment]
lgtm
